# Generated by Django 3.2.8 on 2021-10-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shopitem_shop_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='shop_info',
            field=models.CharField(max_length=64),
        ),
    ]
