# Generated by Django 3.2.8 on 2021-10-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_shopitem_shop_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopItem',
        ),
    ]
